const nftDataObject=[
    {
        id:"1",
        nftName:"The Orbitians",
        minted:"09.30.2022",
        author: "BlueWhale",
        description: "The Orbitians is a collection of 10,000 unique NFTs on the Ethereum blockchain, There are all sorts of beings in the NFT Universe. The most advanced and friendly of the bunch are Orbitians. They live in a metal space machines, high up in the sky and only have one foot on Earth. These Orbitians are a peaceful race, but they have been at war with a group of invaders for many generations. The invaders are called Upside-Downs, because of their inverted bodies that live on the ground, yet do not know any other way to be. Upside-Downs believe that they will be able to win this war if they could only get an eye into Orbitian territory, so they've taken to make human beings their target.",
        details:[ "View on Etherscan", "View Original"],
        tags:["Space","Abstract","Animals"],
        avatar:require('./Avatars/BlueWhale.png'),
        NFT:require('./NFT/TheOrbitians.png'),
    },
    {
        id:"2",
        nftName:"Space Walking",
        minted:"10.12.2022",
        author: "DigiLab",
        description: "Space Walking ipsum dolor sit amet, consectetur adipiscing elit. Quisque id nunc suscipit, hendrerit eros at, congue justo. Nunc viverra dui sed orci feugiat maximus. Vivamus suscipit, diam mollis venenatis fermentum, leo purus mattis nisl, sed pharetra justo erat at ex. Morbi nisl sapien, sagittis a laoreet id, viverra nec odio. Vivamus sit amet urna in massa aliquet bibendum. Phasellus congue erat at lacus venenatis sollicitudin. Ut laoreet dui vulputate aliquam aliquet. Fusce interdum felis tellus, ac interdum velit egestas a. Cras semper turpis quis sapien cursus feugiat. Vestibulum consequat nisi nec porta pretium. Donec ac ligula neque. Integer lobortis rhoncus eros et viverra. Ut efficitur efficitur tempor. Sed ut lacus eu est mollis fringilla. Proin at pulvinar turpis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
        details:[ "View on Etherscan", "View Original", "Whatever else"],
        tags:["Planets","Space","Art"],
        avatar:require('./Avatars/DigiLab.png'),
        NFT:require('./NFT/SpaceWalking.png'),
    },
    {
        id:"3",
        nftName:"Gravity",
        minted:"06.17.2022",
        author: "GravityOne",
        description: "Gravity ipsum dolor sit amet, consectetur adipiscing elit. Fusce maximus, neque sed pellentesque auctor, arcu enim consequat nunc, eu varius velit nulla sit amet metus. Praesent sapien ante, feugiat at placerat eget, fermentum vel tortor. Phasellus volutpat rhoncus porta. Vestibulum laoreet a tellus sit amet sollicitudin. Duis tincidunt magna magna, ac tempus ligula tempus vitae. Suspendisse sit amet risus eget nisi dapibus lacinia in sed ipsum. Fusce at nulla ac tellus ultrices dictum. Donec a metus lectus. Suspendisse dapibus scelerisque augue in efficitur.",
        details:[ "View on Etherscan", "View Original", "Whatever else"],
        tags:["Abstract","Planets","Space"],
        avatar:require('./Avatars/GravityOne.png'),
        NFT:require('./NFT/Gravity.png'),
    },
    {
        id:"4",
        nftName:"Stellar Girl",
        minted:"03.05.2022",
        author: "Juanie",
        description: "Stellar Girl euismod metus sagittis justo faucibus viverra at ut felis. Nulla commodo, ipsum a commodo finibus, est ligula tristique turpis, ac ultrices dolor augue sed lacus. Pellentesque leo sapien, tempor ac faucibus et, tristique ac sem. Fusce vehicula maximus laoreet. Cras tortor elit, tempor condimentum feugiat vitae, molestie eu lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Praesent quis ullamcorper urna.",
        details:[ "View on Etherscan", "View Original", "Whatever else"],
        tags:["Art","Space","Girl"],
        avatar:require('./Avatars/Juanie.png'),
        NFT:require('./NFT/StellarGirl.png'),
    },
    {
        id:"5",
        nftName:"Stuff That Matter",
        minted:"07.02.2022",
        author: "KeepItReal",
        description: "Stuff that matter congue mauris in nisl ornare viverra. Maecenas mattis, sapien ut porta viverra, augue turpis maximus odio, imperdiet suscipit nisi augue nec sapien. Aenean malesuada quis libero sit amet fermentum. Suspendisse rhoncus sit amet erat in fringilla. Integer varius sit amet arcu nec dapibus. In scelerisque bibendum lacus, sit amet rhoncus dolor dictum vitae. Sed urna justo, maximus egestas blandit ut, auctor eu ligula. Fusce nec nunc volutpat, elementum ligula quis, pretium mi. Donec felis ex, dapibus sit amet diam dignissim, suscipit elementum quam. Proin odio erat, pretium at mattis a, viverra vitae nunc. Proin vel ex faucibus, iaculis eros quis, feugiat erat. Integer sit amet varius nunc, sit amet egestas sapien. Phasellus aliquam finibus nibh, id ornare purus. Fusce est eros, ultrices quis ex blandit, dapibus efficitur turpis.",
        details:[ "View on Etherscan", "View Original", "Whatever else"],
        tags:["Abstract","Things","Dreams"],
        avatar:require('./Avatars/KeepItReal.png'),
        NFT:require('./NFT/StuffThatMatter.png'),
    },
    {
        id:"6",
        nftName:"Space Animal",
        minted:"04.23.2022",
        author: "MrFox",
        description: "Nulla space animal fermentum quis arcu id tincidunt. Phasellus porta turpis consequat, pulvinar nisl vitae, dignissim urna. Morbi ut lorem congue, tempor elit ac, imperdiet purus. Duis bibendum ligula a blandit convallis. In eget tincidunt arcu. Duis cursus felis magna, quis dapibus sapien tempor eu. Mauris vehicula maximus dui, et ornare lectus porttitor vitae. Aliquam erat volutpat. Phasellus euismod mauris ante, at ornare justo faucibus vel. Duis a nunc ut purus tempus congue. Vivamus vel interdum ligula, sit amet consequat turpis. Duis sed bibendum magna, et dapibus risus.",
        details:[ "CGI", "Animals", "Space"],
        tags:["Animation","Planets","Animal"],
        avatar:require('./Avatars/MrFox.png'),
        NFT:require('./NFT/SpaceAnimal.png'),
    },
]
export default nftDataObject